export const portfolioConfig = {
  personal: {
    fullName: 'Sagar Pandey',
    initials: 'SP',
    title: 'Solution Architect',
    subtitle: 'Azure · M365 · AI/ML · Reactjs · Node.js',
    email: 'sagar.pandey@example.com',
    phone: '+1 (206) 555-0198',
    location: 'Mumbai, India',
    linkedIn: 'linkedin.com/in/sagarpandey88',
    resumeUrl: '/resume.pdf',
    summary: [
      'Solution Architect with 15+ years of experience designing scalable, secure, and cost-effective cloud solutions across enterprise environments. Deep expertise in Azure cloud services, Microsoft 365 integration, Node.js microservices, and AI/ML pipeline architecture.',
      'Proven track record of translating complex business requirements into elegant technical architectures, leading cross-functional engineering teams, and partnering with executive stakeholders to define long-term platform strategy.',
      'Passionate about leveraging AI/ML capabilities — from Azure AI Foundry and Cognitive Services to bespoke ML pipelines — to create intelligent, adaptive systems that give organizations a measurable competitive edge.',
    ],
  },
  skills: {
    cloud: [
      'Azure App Services',
      'Azure Functions',
      'Azure Blob Storage',
      'Cosmos DB',
      'Azure AI Services',
      'Azure DevOps',
      'Azure API Management',
      'Azure Service Bus',
      'Azure Key Vault',
    ],
    development: [
      'Node.js',
      'TypeScript',
      'REST & GraphQL APIs',
      'Microservices',
      'Serverless Architecture',
      'React / Next.js',
      'Docker',
      'CI/CD Pipelines',
      'Event-Driven Architecture',
      'Infrastructure as Code',
    ],
    aiml: [
      'Azure AI Foundry',
      'Azure OpenAI Service',
      'Azure Cognitive Services',
      'Prompt Engineering',
      'RAG Architecture',
      'Langchain and LangGraph',
    ],
    microsoft: [
      'Microsoft 365',
      'SharePoint Online',
      'Microsoft Teams',
      'Power Platform',
      'Power Automate',
      'Power Apps',
      'Microsoft Graph API'    ],
  },
  stats: [
    { value: '15+', label: 'Years Experience' },
    { value: '30+', label: 'Azure Projects' },
    { value: '10+', label: 'Enterprise Clients' },
    { value: '$3M+', label: 'Cost Savings Delivered' },
  ],
  experience: [
    {
      title: 'Solution Architect',
      company: 'NovaTech Solutions',
      period: '2021 – Present',
      location: 'Seattle, WA',
      highlights: [
        'Architected a cloud-native Azure platform serving 1.2M+ daily active users, reducing infrastructure costs by 38% through strategic use of serverless and containerized workloads.',
        'Led a cross-functional team of 14 engineers to deliver an enterprise M365 integration suite connecting SharePoint, Teams, and Power Platform to a custom Node.js microservices layer, cutting manual workflows by 60%.',
        'Designed and deployed an Azure AI Foundry–powered document intelligence pipeline processing 500K+ documents monthly, improving extraction accuracy to 97.4%.',
        'Established architectural governance standards and conducted design reviews for 20+ projects annually, ensuring scalability, security, and compliance with SOC 2 and ISO 27001.',
        'Partnered with C-suite stakeholders to define a 3-year cloud strategy roadmap, securing $4.2M in platform investment.',
      ],
      tags: ['Azure', 'Node.js', 'AI Foundry', 'M365', 'Microservices'],
    },
    {
      title: 'Senior Cloud Solutions Architect',
      company: 'Meridian Digital Group',
      period: '2018 – 2021',
      location: 'San Francisco, CA',
      highlights: [
        'Re-architected a monolithic application into 22 Node.js microservices on Azure App Services, achieving 99.98% uptime and a 45% reduction in time-to-deploy.',
        'Built an Azure Cognitive Services–backed sentiment analysis engine integrated into Microsoft Teams, enabling real-time customer support triage and reducing average resolution time by 28%.',
        'Designed a Cosmos DB multi-region data layer with automatic failover, supporting global expansion to 8 new markets with sub-100ms read latencies.',
        'Implemented Power Platform solutions for 6 enterprise clients, automating 120+ business processes and eliminating an estimated 18,000 hours of manual work annually.',
      ],
      tags: ['Azure App Services', 'Cosmos DB', 'Cognitive Services', 'Power Platform'],
    },
    {
      title: 'Lead Backend Engineer',
      company: 'Cloudbridge Systems',
      period: '2015 – 2018',
      location: 'Austin, TX',
      highlights: [
        'Led development of a Node.js API gateway handling 40M+ monthly requests with Azure API Management, improving security posture with OAuth 2.0 and rate limiting policies.',
        'Integrated Microsoft Graph API into a unified productivity dashboard for a 10,000-employee enterprise client, consolidating M365 data into a single actionable interface.',
        'Mentored a team of 6 junior developers, implementing code review standards that reduced production bugs by 52% over 12 months.',
        'Designed Azure Service Bus event-driven workflows that decoupled 8 upstream systems, reducing integration failures by 73%.',
      ],
      tags: ['Node.js', 'Azure API Management', 'Graph API', 'Service Bus'],
    },
    {
      title: 'Software Engineer',
      company: 'Pixel & Parse Inc.',
      period: '2012 – 2015',
      location: 'Chicago, IL',
      highlights: [
        'Developed RESTful Node.js APIs consumed by web and mobile clients with 300K+ registered users.',
        'Contributed to early SharePoint Online migrations for 3 enterprise clients, establishing reusable deployment playbooks.',
        'Built data ingestion pipelines on Azure Blob Storage with automated transformation logic, reducing data processing latency by 65%.',
      ],
      tags: ['Node.js', 'SharePoint', 'Azure Storage', 'REST APIs'],
    },
  ],
  projects: [
    {
      title: 'Enterprise AI Knowledge Hub',
      description:
        'A Retrieval-Augmented Generation (RAG) platform built on Azure AI Foundry and Azure OpenAI Service, enabling employees to query internal knowledge bases through a natural-language Teams interface.',
      impact: [
        'Reduced average internal query resolution time from 4.2 hours to 8 minutes',
        'Indexed 2M+ documents across SharePoint, Confluence, and Azure Blob Storage',
        'Achieved 94% user satisfaction rating within 3 months of launch',
      ],
      stack: ['Azure AI Foundry', 'Azure OpenAI', 'Node.js', 'Teams', 'SharePoint', 'Cosmos DB'],
        repoUrl: '',
        demoUrl: '',
        icon: 'Brain',
    },
    {
      title: 'Global M365 Productivity Platform',
      description:
        'A unified Microsoft 365 integration layer connecting SharePoint, Teams, Power Automate, and a custom Node.js backend to automate HR, procurement, and compliance workflows across 12 international offices.',
      impact: [
        'Automated 200+ business processes previously handled manually',
        'Reduced process cycle time by an average of 71% across departments',
        'Delivered $1.8M in measured operational savings in year one',
      ],
      stack: ['M365', 'Power Platform', 'Graph API', 'Node.js', 'Azure Functions', 'Azure AD'],
        repoUrl: '',
        demoUrl: '',
        icon: 'Layers',
    },
    {
      title: 'Cloud-Native Microservices Platform',
      description:
        'Re-architecture of a legacy enterprise platform into a containerized microservices ecosystem on Azure Kubernetes Service, with full CI/CD automation through Azure DevOps.',
      impact: [
        'Scaled from 50K to 1.2M daily active users without infrastructure rework',
        'Decreased deployment frequency from monthly to multiple times per day',
        'Cut cloud infrastructure spend by 38% through right-sizing and autoscaling',
      ],
      stack: ['AKS', 'Node.js', 'Azure DevOps', 'Cosmos DB', 'Azure Service Bus', 'Key Vault'],
        repoUrl: 'https://github.com/test',
        demoUrl: 'https://github.com/test',
        icon: 'Server',
    },
    {
      title: 'Real-Time ML Analytics Engine',
      description:
        'A machine learning pipeline on Azure Machine Learning that ingests streaming telemetry data, applies predictive models, and surfaces anomaly alerts into Power BI dashboards and Teams notifications.',
      impact: [
        'Reduced equipment downtime by 34% through predictive maintenance alerts',
        'Processed 12TB of telemetry data monthly with sub-second latency',
        'Achieved 91% precision in anomaly detection, exceeding baseline by 22 points',
      ],
      stack: ['Azure ML', 'Azure Functions', 'Node.js', 'Power BI', 'Cosmos DB', 'Event Hubs'],
        repoUrl: '',
        demoUrl: '',
        icon: 'Cpu',
    },
  ],
  certifications: [
    { name: 'Microsoft Certified: Azure Solutions Architect Expert', issuer: 'Microsoft', year: '2023' },
    { name: 'Microsoft Certified: Azure AI Engineer Associate', issuer: 'Microsoft', year: '2023' },
    { name: 'Microsoft 365 Certified: Enterprise Administrator Expert', issuer: 'Microsoft', year: '2022' },
    { name: 'AWS Certified Solutions Architect – Associate', issuer: 'Amazon Web Services', year: '2021' },
    { name: 'Certified Kubernetes Administrator (CKA)', issuer: 'CNCF', year: '2022' },
  ],
  education: [
    {
      degree: 'M.S. Computer Science',
      school: 'University of Washington',
      details: 'Concentration: Distributed Systems · 2013',
    },
    {
      degree: 'B.S. Computer Engineering',
      school: 'University of Illinois Urbana-Champaign',
      details: 'Magna Cum Laude · 2011',
    },
  ],
  continuousLearning: ['Azure Architecture Center', 'MIT OpenCourseWare ML', 'Node.js Patterns', 'CNCF Landscape'],
  tagColors: {
    Azure: 'bg-sky-600 text-white',
    'Node.js': 'bg-green-600 text-white',
    'AI Foundry': 'bg-amber-400 text-slate-900',
    M365: 'bg-blue-600 text-white',
    Microservices: 'bg-slate-800 text-slate-200 border border-slate-700',
    'Azure App Services': 'bg-sky-600 text-white',
    'Cosmos DB': 'bg-teal-600 text-white',
    'Cognitive Services': 'bg-amber-400 text-slate-900',
    'Power Platform': 'bg-blue-600 text-white',
    'Azure API Management': 'bg-sky-600 text-white',
    'Graph API': 'bg-blue-600 text-white',
    'Service Bus': 'bg-slate-700 text-slate-200',
    SharePoint: 'bg-blue-600 text-white',
    'Azure Storage': 'bg-sky-600 text-white',
    'REST APIs': 'bg-emerald-600 text-white',
  },
  navLinks: [
    { id: 'summary', label: 'About' },
    { id: 'skills', label: 'Skills' },
  
    { id: 'projects', label: 'Projects' },
    { id: 'certifications', label: 'Credentials' },
    { id: 'contact', label: 'Contact' },
  ] as { id: 'summary' | 'skills' | 'projects' | 'certifications' | 'contact'; label: string }[],
};
